name: Testing

on:
  push:
    # Inputs the workflow accepts.
    branches: [ "main" ]

jobs:
  Build:
    runs-on: windows-latest
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
    # strategy:
     # matrix:
       # windows-version: [x86, x64]?
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download DOT.NET
        run: choco install dotnetfx
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Download VSTools
        run: choco install visualstudio2022buildtools
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: foobar.txt
          compression-level: 9 # maximum compression
          #$env:GITHUB_WORKSPACE/
        

        
     # - name: Build app for release 
     #   run: msbuild src\a.sln -t:rebuild -verbosity:diag -property:Configuration=Release

  #Unit-Testing:
  #  runs-on: windows-latest
  #  steps:
    
